# Theme config.

[[menu.main]]
  identifier = "about"
  name = 'About'
  url = '/about'
  weight = 2

[[menu.main]]
  identifier = "setup"
  name = 'PC Specs'
  url = '/pc-specs'
  weight = 3

[[menu.main]]
  identifier = "work-with-me"
  name = 'Work With Me'
  url = '/work-with-me'
  weight = 4

[[menu.main]]
  identifier = "charity"
  name = 'Charity'
  url = '/charity'
  weight = 5

[[menu.main]]
  identifier = "socials"
  name = 'Socials'
  url = '/socials'
  weight = 6
