# Theme config.

[[menu.main]]
  identifier = "Home"
  name = 'Home'
  url = '/home'
  weight = 1

[[menu.main]]
  identifier = "about"
  name = 'About'
  url = '/about'
  weight = 2

[[menu.main]]
  identifier = "setup"
  name = 'Setup'
  url = '/setup'
  weight = 3

[[menu.main]]
  identifier = "socials"
  name = 'Socials'
  url = '/socials'
  weight = 4
